globals:
  - id: total_energy
    type: float
    restore_value: yes
    initial_value: '0.0'

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    icon: mdi:wifi

  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

  - platform: homeassistant
    name: "Temperature Sensor From Home Assistant"
    id: current_temperature
    entity_id: sensor.office_air_quality_monitor_temperature

  # Small buttons over ADC - see https://templates.blakadder.com/nous_A5T.html
  - platform: adc
    pin: VCC
    id: a0_vcc
    update_interval: 1s
    internal: true
    filters:
      - clamp:
          min_value: 0
          max_value: 4
          ignore_out_of_range: true
      - timeout:
          timeout: 1s
          value: 4
    on_value_range:
      - below: 1.5
        then:
          - switch.toggle: relay3
      - above: 1.5
        below: 2.5
        then:
          - switch.toggle: relay2
      - above: 2.5
        below: 3.5
        then:
          - switch.toggle: relay1

  - platform: cse7766
    current:
      name: "Current"
      filters:
        - throttle: 10s

    voltage:
      name: "Voltage"
      filters:
        - multiply: 2.4
        - throttle: 10s

    power:
      name: "Power"
      id: power_sensor
      filters:
        - multiply: 2.4
        - throttle: 1s

    energy:
      name: "Energy"
      id: energy
      unit_of_measurement: kWh
      filters:
        # Multiplication factor from W to kW is 0.001
        # and multiple by 2.4 because of the voltage factor
        - multiply: 0.0024
        - throttle: 1s
      on_value:
        then:
          - lambda: |-
              static float previous_energy_value = 0.0;
              float current_energy_value = id(energy).state;
              id(total_energy) += current_energy_value - previous_energy_value;
              previous_energy_value = current_energy_value;

  - platform: template
    name: "Total Energy"
    unit_of_measurement: kWh
    device_class: "energy"
    state_class: "total_increasing"
    icon: "mdi:lightning-bolt"
    accuracy_decimals: 3
    lambda: |-
      return id(total_energy);
    update_interval: 60s

