name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/publish-common.yml
    with:
      files: nous-a5t.yml
      name: ESPHome Nous A5T
